name: go
on: [push]
jobs:

  fmt:
    name: fmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: 1.12
    - uses: actions/checkout@v1
    - run: diff -u <(echo -n) <(gofmt -d ./)

  gqlgen:
    name: gqlgen
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: 1.12
    - uses: actions/checkout@v1
    - name: check if gqlgen has a diff
      run: |
        go install github.com/99designs/gqlgen
        echo $GOPATH
        echo $PATH
        make gen

        git diff --exit-code || echo '\n\nPlease update the generated code (by running `make deps`).'

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: 1.12
    - uses: actions/checkout@v1
    - run: make test
